---
title: "Coeff analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(scLinear)
library(tidyverse)
library(ggplot2)
```

## feature impact analysis PBMC10K

```{r}
pbmc10k <- readRDS("./../local/PBMC10K_predicted.rds")

pipe <- create_adt_predictor()
pipe <- load_pretrained_model(pipe, model = "all")

feature_importance <- function(pipe, gexp, slot = "counts", normalize = TRUE){
    gexp_matrix <- Seurat::GetAssayData(gexp, slot = slot)
  
    if(normalize){
    ## normalize data GEX
    sce <- SingleCellExperiment::SingleCellExperiment(list(counts = gexp_matrix))
    clusters <- scran::quickCluster(sce)
    sce <- scran::computeSumFactors(sce, clusters=clusters)
    sce <- scuttle::logNormCounts(sce, pseudo.count = 1, center.size.factors = FALSE, log = FALSE)
    gexp_matrix <- sce@assays@data@listData[["normcounts"]]
    gexp_matrix <- base::log1p(gexp_matrix)
  }

  
  gexp_matrix <- Matrix::t(gexp_matrix)

  gexp_matrix_py <- reticulate::r_to_py(as.matrix(gexp_matrix))

  feature_imp <- pipe$feature_importance(gexp_matrix_py, gex_names = colnames(gexp_matrix))
  
  colnames(feature_imp) <- pipe$gex_names$to_list()
  rownames(feature_imp) <- pipe$adt_names$to_list()
  
  return(feature_imp)
}


fi <- feature_importance(pipe, pbmc10k@assays$RNA, slot = "counts", normalize = TRUE)


write.table(fi, "./../local/PBMC/feature_importance_pbmc10k.txt", sep = "\t", row.names = TRUE, col.names = TRUE, quote = FALSE)

saveRDS(fi, "./../local/PBMC/feature_importance_pbmc10k.rds")

```


```{r}
fi <- readRDS("./../local/PBMC/feature_importance_pbmc10k.rds")

fi <- t(fi)
fi_long <- fi %>% as.data.frame() %>% rownames_to_column("gene") %>% pivot_longer(!gene , values_to = "value", names_to = "protein")

fi_long <- fi_long %>% dplyr::filter(protein %in% c("CD3", "CD19"))


fi_max_slice <- fi_long %>% group_by(protein) %>% slice_max(value, n = 20)
fi_min_slice <- fi_long %>% group_by(protein) %>% slice_min(value, n = 20)
fi_slice <- rbind(fi_max_slice, fi_min_slice) %>% unique()
used_top_impact_genes <- fi_slice %>% pull("gene") %>% unique()


impact_matrix <-fi[rownames(fi) %in% used_top_impact_genes,]
impact_matrix <- t(impact_matrix)

impact_matrix <- impact_matrix[rownames(impact_matrix) %in% c("CD3", "CD19"),]

library(pheatmap)

svg("./../local/PBMC/heatmap_impact_mtarix_pbmc10k.svg", height = 10, width = 20)
  pheatmap(impact_matrix)
dev.off()


```

```{r}




KEGG_plot <- function(fi_long,  Protein = "CD3", n = 20, n_pathway = 10){
library(enrichR)
library(pals)
  
Up <- fi_long %>% dplyr::filter(protein %in% Protein) %>% group_by(protein) %>% slice_max(value ,n = n) %>% pull(gene)
Down <- fi_long %>% dplyr::filter(protein %in% Protein) %>% group_by(protein) %>% slice_min(value ,n = n) %>% pull(gene)

print(Up)
print(Down)

  ## KEGG pathways
  KEGG_up <- enrichr(Up, "KEGG_2021_Human")
  KEGG_up <- KEGG_up$KEGG_2021_Human
  KEGG_up <- head(KEGG_up, n_pathway)
  #if(nrow(KEGG_up)>0){KEGG_up$Term <- paste0(KEGG_up$Term, "_up")}
  KEGG_up$Adjusted.P.value <- -log10(KEGG_up$Adjusted.P.value)
  
  KEGG_down <- enrichr(Down, "KEGG_2021_Human")
  KEGG_down <- KEGG_down$KEGG_2021_Human
  KEGG_down <- head(KEGG_down, n_pathway)
  #if(nrow(KEGG_down)>0){KEGG_down$Term <- paste0(KEGG_down$Term, "_down")}
  KEGG_down$Adjusted.P.value <- log10(KEGG_down$Adjusted.P.value)
  
  KEGG <- rbind(KEGG_up, KEGG_down)
  #KEGG <- KEGG[order(KEGG$Adjusted.P.value, decreasing = TRUE),]
  
  table_KEGG <- KEGG %>% dplyr::select(Term, Overlap, Adjusted.P.value, Genes) %>% dplyr::rename("-log10(Adjusted.P.value)" = Adjusted.P.value)
alpha <- 0.05

  p_KEGG <- ggplot(KEGG, aes(x=reorder(Term, Adjusted.P.value), y=Adjusted.P.value, fill=Adjusted.P.value)) +
    geom_bar(stat="identity") + coord_flip() + theme_bw() +
    xlab("KEGG Pathways") + ylab("Adjusted Pvalue (-log10)") +
    scale_fill_gradientn(colors = coolwarm(20)) + annotate(geom = "hline",
    y = c(-log10(alpha)), yintercept = c(-log10(alpha)), linetype = "dashed", color = "black", size = 0.2) +
    annotate(geom = "hline", y = c(log10(alpha)), yintercept = c(log10(alpha)), linetype = "dashed", color = "black", size = 0.2)

return(p_KEGG)
}

p <- KEGG_plot(fi_long, Protein = "CD3", n_pathway = 6)
p1 <- p + ggtitle("PBMC10K, CD3, KEGG pathways")

p <- KEGG_plot(fi_long, Protein = "CD19", n_pathway = 6)
p2 <- p + ggtitle("PBMC10K, CD19, KEGG pathways")

library(patchwork)
svg("./../local/PBMC/PBMC10K_KEGG_CD3_CD19.svg", height = 8, width = 20)
   p1 + p2
dev.off()


 

```


## feature impact analysis Visum Tonsil

```{r}
sobj <- readRDS("./../local/Visium/visium_10xGenomics_predicted(withNeurIPS).rds")
tonsil <- sobj$tonsil

pipe <- create_adt_predictor()
pipe <- load_pretrained_model(pipe, model = "all")

feature_importance <- function(pipe, gexp, slot = "counts", normalize = TRUE){
    gexp_matrix <- Seurat::GetAssayData(gexp, slot = slot)
  
    if(normalize){
    ## normalize data GEX
    sce <- SingleCellExperiment::SingleCellExperiment(list(counts = gexp_matrix))
    clusters <- scran::quickCluster(sce)
    sce <- scran::computeSumFactors(sce, clusters=clusters)
    sce <- scuttle::logNormCounts(sce, pseudo.count = 1, center.size.factors = FALSE, log = FALSE)
    gexp_matrix <- sce@assays@data@listData[["normcounts"]]
    gexp_matrix <- base::log1p(gexp_matrix)
  }

  
  gexp_matrix <- Matrix::t(gexp_matrix)

  gexp_matrix_py <- reticulate::r_to_py(as.matrix(gexp_matrix))

  feature_imp <- pipe$feature_importance(gexp_matrix_py, gex_names = colnames(gexp_matrix))
  
  colnames(feature_imp) <- pipe$gex_names$to_list()
  rownames(feature_imp) <- pipe$adt_names$to_list()
  
  return(feature_imp)
}


fi <- feature_importance(pipe, tonsil@assays$RNA, slot = "counts", normalize = TRUE)


write.table(fi, "./../local/Visium/feature_importance_tonsil.txt", sep = "\t", row.names = TRUE, col.names = TRUE, quote = FALSE)

saveRDS(fi, "./../local/Visium/feature_importance_tonsil.rds")

```


```{r}
fi <- readRDS("./../local/Visium/feature_importance_tonsil.rds")

fi <- t(fi)
fi_long <- fi %>% as.data.frame() %>% rownames_to_column("gene") %>% pivot_longer(!gene , values_to = "value", names_to = "protein")

fi_long <- fi_long %>% dplyr::filter(protein %in% c("CD3", "CD19"))


fi_max_slice <- fi_long %>% group_by(protein) %>% slice_max(value, n = 20)
fi_min_slice <- fi_long %>% group_by(protein) %>% slice_min(value, n = 20)
fi_slice <- rbind(fi_max_slice, fi_min_slice) %>% unique()
used_top_impact_genes <- fi_slice %>% pull("gene") %>% unique()


impact_matrix <-fi[rownames(fi) %in% used_top_impact_genes,]
impact_matrix <- t(impact_matrix)

impact_matrix <- impact_matrix[rownames(impact_matrix) %in% c("CD3", "CD19"),]

library(pheatmap)

svg("./../local/Visium/heatmap_impact_mtarix_tonsil.svg", height = 10, width = 20)
  pheatmap(impact_matrix)
dev.off()


```

```{r}




KEGG_plot <- function(fi_long,  Protein = "CD3", n = 20, n_pathway = 10){
library(enrichR)
library(pals)
  
Up <- fi_long %>% dplyr::filter(protein %in% Protein) %>% group_by(protein) %>% slice_max(value ,n = n) %>% pull(gene)
Down <- fi_long %>% dplyr::filter(protein %in% Protein) %>% group_by(protein) %>% slice_min(value ,n = n) %>% pull(gene)

print(Up)
print(Down)

  ## KEGG pathways
  KEGG_up <- enrichr(Up, "KEGG_2021_Human")
  KEGG_up <- KEGG_up$KEGG_2021_Human
  KEGG_up <- head(KEGG_up, n_pathway)
  #if(nrow(KEGG_up)>0){KEGG_up$Term <- paste0(KEGG_up$Term, "_up")}
  KEGG_up$Adjusted.P.value <- -log10(KEGG_up$Adjusted.P.value)
  
  KEGG_down <- enrichr(Down, "KEGG_2021_Human")
  KEGG_down <- KEGG_down$KEGG_2021_Human
  KEGG_down <- head(KEGG_down, n_pathway)
  #if(nrow(KEGG_down)>0){KEGG_down$Term <- paste0(KEGG_down$Term, "_down")}
  KEGG_down$Adjusted.P.value <- log10(KEGG_down$Adjusted.P.value)
  
  KEGG <- rbind(KEGG_up, KEGG_down)
  #KEGG <- KEGG[order(KEGG$Adjusted.P.value, decreasing = TRUE),]
  
  table_KEGG <- KEGG %>% dplyr::select(Term, Overlap, Adjusted.P.value, Genes) %>% dplyr::rename("-log10(Adjusted.P.value)" = Adjusted.P.value)
alpha <- 0.05

  p_KEGG <- ggplot(KEGG, aes(x=reorder(Term, Adjusted.P.value), y=Adjusted.P.value, fill=Adjusted.P.value)) +
    geom_bar(stat="identity") + coord_flip() + theme_bw() +
    xlab("KEGG Pathways") + ylab("Adjusted Pvalue (-log10)") +
    scale_fill_gradientn(colors = coolwarm(20)) + annotate(geom = "hline",
    y = c(-log10(alpha)), yintercept = c(-log10(alpha)), linetype = "dashed", color = "black", size = 0.2) +
    annotate(geom = "hline", y = c(log10(alpha)), yintercept = c(log10(alpha)), linetype = "dashed", color = "black", size = 0.2)

return(p_KEGG)
}

p <- KEGG_plot(fi_long, Protein = "CD3", n_pathway = 6)
p1 <- p + ggtitle("Tonsil, CD3, KEGG pathways")

p <- KEGG_plot(fi_long, Protein = "CD19", n_pathway = 6)
p2 <- p + ggtitle("Tonsil, CD19, KEGG pathways")

library(patchwork)
svg("./../local/Visium/Tonsil_KEGG_CD3_CD19.svg", height = 8, width = 20)
   p1 + p2
dev.off()

p1 + p2
 

```