---
title: "Analysis"
author: "Daniel Hanhart"
date: "3/16/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(scLinear)
library(tidyverse)
library(ggplot2)
library(Seurat)
library(svglite)
library(Metrics)
library(pals)
library(ggpubr)
library(DropletUtils)
library(Matrix)
library(grid)
library(ggrepel)
source("helper_functions.R")
# quickly test if py modules can be loaded
pipe <- create_adt_predictor()
rm(pipe)

set.seed(42)
```

## PBMC5K

### Create Seurat object from raw data

```{r}
# create seurat object from pbmc5k data
## Some of the protein names in pbmc5k differ from the ones used in the NeurIPS data (CD8a -> CD8, PD-1 -> CD279). Create name mapping."
map_names <- data.frame(
	pbmc5k = c("CD3", "CD4", "CD8a", "CD11b", "CD14", "CD15", "CD16", "CD19", "CD20", "CD25", "CD27", "CD28", "CD34", "CD45RA", "CD45RO", "CD56", "CD62L", "CD69", "CD80", "CD86", "CD127", "CD137", "CD197", "CD274", "CD278", "CD335", "PD-1", "HLA-DR", "TIGIT", "IgG1", "IgG2a", "IgG2b"),
	neurips = c("CD3", "CD4", "CD8", "CD11b", "CD14", "CD15", "CD16", "CD19", "CD20", "CD25", "CD27", "CD28", "CD34", "CD45RA", "CD45RO", "CD56", "CD62L", "CD69", "CD80", "CD86", "CD127", "CD137", "CD197", "CD274", "CD278", "CD335", "CD279", "HLA-DR", "TIGIT", "IgG1", "IgG2a", "IgG2b")
)

pbmc5k.data <- Seurat::Read10X_h5("./../local/PBMC5K/5k_pbmc_protein_v3_filtered_feature_bc_matrix.h5")
rownames(x = pbmc5k.data[["Antibody Capture"]]) <- gsub(pattern = "_[control_]*TotalSeqB", replacement = "",
                                                           x = rownames(x = pbmc5k.data[["Antibody Capture"]]))
rownames(x = pbmc5k.data[["Antibody Capture"]]) <- map_names$neurips[ match(rownames(x = pbmc5k.data[["Antibody Capture"]]), map_names$pbmc5k)]

pbmc5k <- Seurat::CreateSeuratObject(counts = pbmc5k.data[["Gene Expression"]], min.cells = 10, min.features = 1)
pbmc5k[["ADT"]] <- Seurat::CreateAssayObject(pbmc5k.data[["Antibody Capture"]][, colnames(x = pbmc5k)])
Seurat::DefaultAssay(pbmc5k) <- "RNA"

pbmc5k$mito_percent <- Seurat::PercentageFeatureSet(object = pbmc5k, pattern = "^MT-")

saveRDS(pbmc5k, "./../local/pbmc5k_filtered.rds")
rm(pbmc5k.data, pbmc5k, map_names)
gc()
```


### Preprocess PBMC5K data

```{r, fig.widh = 30, fig.height = 5}
pbmc5k <- readRDS("./../local/pbmc5k_filtered.rds")

pbmc5k <- adt_qc(pbmc5k, iso_features = c("IgG1", "IgG2a", "IgG2b"))

## Perform basc preprocessing steps including: lognormalization, removal of doublets, removal of low quality cells, clustering, cell-type annotation
pbmc5k <- scLinear::prepare_data(pbmc5k,
                                   remove_doublets = TRUE,
                                   low_qc_cell_removal = TRUE,
                                   anno_level = c(1,2,3,4),
                                   samples = NULL,
                                   integrate_data = FALSE,
                                   remove_empty_droplets = FALSE,
                                   lower = 100, FDR = 0.01,
                                   annotation_selfCluster = TRUE,
                                   resolution = 0.8,
                                   seed = 42)

##  remove adt based filtered cells 
print("Number of cells filtered based on ADT data")
table(pbmc5k@meta.data$adt_filter )
pbmc5k <- subset(pbmc5k, subset = adt_filter == FALSE)

## Normalize ADT data
pbmc5k <- Seurat::NormalizeData(pbmc5k, normalization.method = "CLR", margin = 2, assay = "ADT")

DimPlot(pbmc5k, group.by = "seurat_clusters")
DimPlot(pbmc5k, group.by = "cell_type_2")
DimPlot(pbmc5k, group.by = "seurat_clusters", cells = colnames(pbmc5k)[pbmc5k@meta.data$cell_type_2 == "Unassigned"]
)
VlnPlot(pbmc5k, group.by = "cell_type_2", features = "nFeature_RNA")

pbmc5k <- subset(pbmc5k, subset = seurat_clusters != "12")
DimPlot(pbmc5k, group.by = "cell_type_2")

saveRDS(pbmc5k, "./../local/PBMC5K_prepared2.rds")
rm(pbmc5k)
gc()
```



### UMAP

```{r}
pbmc5k <- readRDS("./../local/PBMC5K_prepared2.rds")

p <- DimPlot(pbmc5k, group.by = "cell_type_2", pt.size = 0.05) + ggtitle("Cell types") +
  scale_color_manual(values = c("#BE0032","#008856","#0067A5", "#F3C300")) + theme_bw()
p
ggsave(filename = "./../local/umap_pbmc5k.pdf", plot = p, width = 9, height = 6, units = "cm")
rm(p, pbmc5k)
gc()
```

### predict PBMC5K with scLinear

```{r}
pbmc5k <- readRDS("./../local/PBMC5K_prepared2.rds")

## load pretrained predictor model scLinear
pipe <- create_adt_predictor()
pipe <- load_pretrained_model(pipe, model = "all")
assay_predicted <- adt_predict(pipe, pbmc5k@assays$RNA, normalize = TRUE)

eval_res <- evaluate_predictor(pipe, pbmc5k@assays$RNA, pbmc5k@assays$ADT)

pbmc5k[["predicted_adt_sclinear"]] <- assay_predicted

saveRDS(pbmc5k, "./../local/PBMC5K_predicted.rds")
rm(assay_predicted, eval_res,pipe)
gc()
```


### bit table (RNA / protein predicted vs protein real)

```{r}
pbmc5k <- readRDS("./../local/PBMC5K_predicted.rds")

adt_real <- as.matrix(pbmc5k@assays[["ADT"]]@data)
adt_real <- adt_real %>% as.data.frame() %>% rownames_to_column("gene") %>% pivot_longer(!gene,names_to = "cell", values_to = "real")
adt_predicted_sclinear <- as.matrix(pbmc5k@assays[["predicted_adt_sclinear"]]@data)
adt_predicted_sclinear <- adt_predicted_sclinear %>% as.data.frame() %>% rownames_to_column("gene") %>% pivot_longer(!gene,names_to = "cell", values_to = "predicted_sclinear")

#### raw RNA counts
rna_raw <- as.matrix(pbmc5k@assays[["RNA"]]@counts)
rna_raw <- rna_raw %>% as.data.frame() %>% rownames_to_column("gene") %>% pivot_longer(!gene,names_to = "cell", values_to = "rna_raw")
#### post processing of RNA data to make it comparable to ADT data

#### add normalized RNA (normalized the same way as used for prediction)
rna_normalized <- as.matrix(scLinear::gexp_normalize(pbmc5k@assays[["RNA"]]@counts))
rna_normalized <- rna_normalized %>% as.data.frame() %>% rownames_to_column("gene") %>% pivot_longer(!gene,names_to = "cell", values_to = "rna_normalized")

adt_real$adt_gene_names_real <- adt_real$gene

adt_predicted_sclinear$adt_gene_names_predicted <- adt_predicted_sclinear$gene

rna_raw$rna_gene_names_raw <- rna_raw$gene

rna_normalized$rna_gene_names_normalized <- rna_normalized$gene


#### post processing of RNA data to make it comparable to ADT data
map <- list(
    list(gexp = c("ITGAM"), adt = c("CD11b")),
    list(gexp = c("FUT4"), adt = c("CD15")),
    list(gexp = c("FCGR3A"), adt = c("CD16")),
    list(gexp = c("MS4A1"), adt = c("CD20")),
    list(gexp = c("IL2RA"), adt = c("CD25")),
    list(gexp = c("NCAM1"), adt = c("CD56")),
    list(gexp = c("SELL"), adt = c("CD62L")),
    list(gexp = c("IL7R"), adt = c("CD127")),
    list(gexp = c("TNFRSF9"), adt = c("CD137")),
    list(gexp = c("CCR7"), adt = c("CD197")),
    list(gexp = c("ICOS"), adt = c("CD278")),
    list(gexp = c("NCR1"), adt = c("CD335")),
    list(gexp = c("PDCD1"), adt = c("CD279")),
    list(gexp = c("HLA-DRA", "HLA-DRB1", "HLA-DRB5"), adt = c("HLA-DR")),
    list(gexp = c("CD3E", "CD3D", "CD3G"), adt = c("CD3")),
    list(gexp = c("CD8A", "CD8B"), adt = c("CD8")),
    list(gexp = c("PTPRC"), adt = c("CD45RA", "CD45RO"))
  )


for (m in map){
  print(paste0("gexp: ", paste0(m$gexp, collapse = ","), "       adt: ", paste0(m$adt, collapse = ",")))
  
  gexp_names <- m$gexp
  adt_names <- m$adt
  
  if((length(gexp_names) == 1) & (length(adt_names) == 1)){
    ## change rna name to adt names
    rna_raw$gene[rna_raw$gene == c(gexp_names)] <- adt_names
    rna_normalized$gene[rna_normalized$gene == c(gexp_names)] <- adt_names
  }else{
    if((length(gexp_names) > 1) & (length(adt_names) == 1)){
      ## map adt name to many gexp names. each gene compared to adt name.
      genes <- gexp_names
      tmp <- adt_real[adt_real$gene == adt_names,]
      adt_real <- adt_real[!(adt_real$gene == adt_names),]
      for (g in genes){
        tmp_2 <- tmp
        tmp_2 $gene <- g
        adt_real <- rbind(adt_real, tmp_2)
      }
      genes <- gexp_names
      tmp <- adt_predicted_sclinear[adt_predicted_sclinear$gene == adt_names,]
      adt_predicted_sclinear <- adt_predicted_sclinear[!(adt_predicted_sclinear$gene == adt_names),]
      for (g in genes){
        tmp_2 <- tmp
        tmp_2 $gene <- g
        adt_predicted_sclinear <- rbind(adt_predicted_sclinear, tmp_2)
      }
      
    }else{
        if((length(gexp_names) == 1) & (length(adt_names) > 1)){
          genes <- adt_names
          tmp <- rna_raw[rna_raw$gene == gexp_names,]
          rna_raw <- rna_raw[!(rna_raw$gene == gexp_names),]
          for (g in genes){
            tmp_2 <- tmp
            tmp_2 $gene <- g
            rna_raw <- rbind(rna_raw, tmp_2)
          }

          genes <- adt_names
          tmp <- rna_normalized[rna_normalized$gene == gexp_names,]
          rna_normalized <- rna_normalized[!(rna_normalized$gene == gexp_names),]
          for (g in genes){
            tmp_2 <- tmp
            tmp_2 $gene <- g
            rna_normalized <- rbind(rna_normalized, tmp_2)
          }
          
        }
    }
  }
  
}


## remove not usefull genes
genes_to_keep <- unique(c(unlist(map, recursive = TRUE), adt_real$gene, adt_predicted_sclinear$gene))
rna_raw <- rna_raw %>% dplyr:: filter(gene %in% genes_to_keep)
rna_normalized <- rna_normalized %>% dplyr:: filter(gene %in% genes_to_keep)

meta <- pbmc5k@meta.data %>% rownames_to_column("cell") %>% dplyr::select("cell","cell_type_2","cell_type_3")

DF <- adt_real %>% full_join(adt_predicted_sclinear, by = c("gene", "cell")) %>%  full_join(rna_normalized, by = c("gene", "cell")) %>% full_join(rna_raw, by = c("gene", "cell")) %>% full_join(meta, by = c("cell"))

DF <- DF %>% arrange(gene)

DF$gene <- factor(DF$gene, levels = unique(DF$gene))

write.table(DF, file = "./../local/PBMC5K/bit_table_pbmc5k_2.csv", sep = ",", col.names = TRUE, row.names = FALSE)
```
#### RNA / protein correlation

##### barplot 
```{r, fig.width= 15, fig.height = 10}
my_pal <- c("#E7E7E0","#A2A187", "#525240", "#03878F", "#F2B531","#ED5958","#68C6A4", "#113245")

DF <- read.table("./../local/PBMC5K/bit_table_pbmc5k_2.csv", header = T, sep=',')
d <- DF %>% na.omit() %>% group_by(gene)  %>%
      summarize(pearson_pADT_vs_rADT = cor(real, predicted_sclinear, method = "pearson"),
                pearson_normalizedRNA_vs_rADT = cor(real, rna_normalized, method = "pearson"),
                pearson_rawRNA_vs_rADT = cor(real, rna_raw, method = "pearson"))


d <- d %>% pivot_longer(!gene, values_to = "pearson", names_to = "comparison") %>% arrange(desc(pearson))

d$gene <- factor(d$gene, levels = unique(d$gene))
d$comparison <- factor(d$comparison, levels = c("pearson_pADT_vs_rADT", "pearson_normalizedRNA_vs_rADT", "pearson_rawRNA_vs_rADT"))

p <- ggplot(d, aes(x = gene, y = pearson, fill = comparison)) + geom_bar(stat="identity", position=position_dodge()) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  scale_fill_manual(values = rev(c(my_pal))[5:length(my_pal)], 
                    labels=c('Predicted ADT vs meassured ADT', 'Normalized RNA expression vs meassured ADT', 'Raw RNA expression vs meassured ATD')) +
  labs(fill = "Pearson Correlation") 
  
p

#ggsave("./../local/panels/Final/Supplementary/1/A.PBMC5K_Protein_RNA_correlation.r1.pdf", width = 20, height = 29/4, units = 'cm')

```
##### Heatmap

```{r, fig.width= 20/2, fig.height = 29/2}
my_pal <- c("#E7E7E0","#A2A187", "#525240", "#03878F", "#F2B531","#ED5958","#68C6A4", "#113245")

DF <- read.table("./../local/PBMC5K/bit_table_pbmc5k_2.csv", header = T, sep=',')
d <- DF %>% na.omit() %>% group_by(gene)  %>%
      summarize(pearson_pADT_vs_rADT = cor(real, predicted_sclinear, method = "pearson"),
                pearson_normalizedRNA_vs_rADT = cor(real, rna_normalized, method = "pearson"),
                pearson_rawRNA_vs_rADT = cor(real, rna_raw, method = "pearson")) %>% column_to_rownames("gene")

d <- d %>% arrange(desc(pearson_pADT_vs_rADT),desc(pearson_normalizedRNA_vs_rADT), desc(pearson_rawRNA_vs_rADT))

p <- ComplexHeatmap::pheatmap(d, scale = "row", 
                   cluster_rows = FALSE, cluster_cols = FALSE,
                   display_numbers = round(as.matrix(d),2),
                   labels_col = c('Predicted ADT\nvs\nMeasured ADT\n\n', 'Normalized RNA Expression\nvs\nMeasured ADT\n\n', 'Raw RNA Expression\nvs\nMeasured ATD\n\n'),
                   legend = TRUE,
                   angle_col = c("0"),
                   color = rev(brewer.rdbu(11))[2:10],
                   number_color = "black", border_color = "white", border = TRUE, border_gp = gpar(col = "black", lty = 1, lwd = 1.5),
                   number_format ="%.2f"  , fontsize_number = 6,
                   column_names_side = c("top"), row_names_side = c("left"),
                   fontsize = 6,
                   fontsize_row = 6,
                   fontsize_col = 5,
                   column_names_max_height = unit(100, "cm"),
                   heatmap_legend_param = list(title = "z score"))

ComplexHeatmap::draw(p, padding = unit(c(0, 0, 20, 0), "mm"))

pdf("./../local/panels/Final/Supplementary/1/D.PBMC5K_Protein_RNA_correlation_heatmap.r1.pdf", width = (20/2)/2.54, height = (29/3 *2)/2.54)
  ComplexHeatmap::draw(p, padding = unit(c(2, 2, 20, 2), "mm"))
dev.off()
```

##### Boxplots
```{r, fig.width= 20/2, fig.height = 29/2}
DF <- read.table("./../local/PBMC5K/bit_table_pbmc5k_2.csv", header = T, sep=',')
df <- DF %>% na.omit()  %>% group_by(gene, adt_gene_names_real, adt_gene_names_predicted, rna_gene_names_normalized, rna_gene_names_raw)  %>%
      summarize('scLinear vs ADT' = cor(real, predicted_sclinear, method = "pearson"),
                'RNA vs ADT' = cor(real, rna_normalized, method = "pearson"))

df <- df %>%pivot_longer( cols = -c(gene,  adt_gene_names_real, adt_gene_names_predicted, rna_gene_names_normalized, rna_gene_names_raw), values_to = "Pearson", names_to = "Comparison")

df$Comparison <- factor(df$Comparison, levels = rev(sort(unique(df$Comparison))))

df$gene_comp <- paste0(df$gene, "_", df$Comparison)


my_pal <- c("#68C6A4", "#A2A187")
df <- df %>% arrange(gene, Comparison)
df$name <- df$gene



df <- df %>% mutate(name = ifelse(Comparison == "RNA vs ADT", rna_gene_names_normalized, adt_gene_names_real))

df$JitteredX <- jitter(rep(0, nrow(df)), amount = 0.2, factor = 1)

jitter_merge <- df %>% ungroup() %>% dplyr::select(name, Comparison, JitteredX)%>% group_by(name, Comparison) %>% summarise(JitteredX_new = mean(JitteredX))

df <- df %>% left_join(jitter_merge, by = c("name", "Comparison")) %>% mutate(JitteredX = JitteredX_new) %>% dplyr::select(-c(JitteredX_new)) %>% mutate(name2 = name)
df$name2[!((df$rna_gene_names_normalized %in% c("CD3", "CD19", "CD14", "CD56")) | (df$adt_gene_names_real %in% c("CD3", "CD19", "CD14", "CD56")))] <- ""

df_reduced <- df %>% ungroup() %>% dplyr::select(c(name, name2, Comparison, Pearson, JitteredX)) %>% distinct()

pos <- position_nudge(df_reduced$JitteredX)
pos2 <- position_nudge(df$JitteredX)
ggplot(df_reduced, aes(x=Comparison, y = Pearson, fill = Comparison, label = name2)) +
  geom_boxplot(show.legend = FALSE) + 
  theme_bw() +
  geom_point(position=pos, size = 0.9) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  scale_fill_manual(values = my_pal) +
  ylab("Pearson") + xlab("") +
  theme(legend.position = "none") +
  geom_label_repel(position = pos,
                  colour = "black", fill = "white", segment.colour="black",
                  min.segment.length = 1,
                  show.legend = TRUE, size = 1.5,
                  box.padding = 0.25, point.padding = 0) +
  theme(axis.ticks.x = element_blank(),
         axis.text.y = element_text(size = 8),
        panel.spacing = unit(0.05, "lines"),
        strip.text.x = element_text(size = 7)) +
  geom_line(data = df, aes(x = Comparison, y = Pearson, group = gene),position = pos2, size = 0.25 , color = "darkblue") 






#ggsave("./../local/panels/Final/Main/1/C.PBMC5K_Pearson_RNA_correlation.v2.pdf", width = 20/2, height = 29/2, units = 'cm')






```

#### Pearson correlation by gene

```{r}
PBMC <- read.table("./../local/PBMC5K/bit_table_pbmc5k_2.csv", header = T, sep=',')
PBMC <- PBMC %>% dplyr::select(-c(rna_normalized, rna_raw))
PBMC <- na.omit(PBMC)
# deduplicate the separation of complexes that was used for RNA/ADT comparison
map <- list(  
    list(gexp = c("HLA-DRA", "HLA-DRB1", "HLA-DRB5"), adt = c("HLA-DR")),
    list(gexp = c("CD3E", "CD3D", "CD3G"), adt = c("CD3")),
    list(gexp = c("CD8A", "CD8B"), adt = c("CD8"))
)
for (m in map){
  print(paste0("gexp: ", paste0(m$gexp, collapse = ","), "       adt: ", paste0(m$adt, collapse = ",")))
  gexp_names <- m$gexp
  adt_name <- m$adt
  for(gexp_name in gexp_names){
    PBMC$gene[PBMC$gene == gexp_name] <- adt_name
  }
}
PBMC <- PBMC %>% distinct()

cors <- PBMC %>% group_by(gene) %>% dplyr::summarise(correlation = cor(real, predicted_sclinear))
ggplot(cors, aes(x=reorder(gene, correlation), y= correlation,fill=correlation)) + geom_bar(stat="identity", col="black") + coord_flip() +
    theme_classic2() + scale_fill_gradientn(colours = inferno(11)) + ylab("Pearson\n(Real vs ScLinear)") + xlab("Protein") + theme(legend.position = "none") +
    ggtitle("PBMC CITE-seq\n(5k cells)") + theme(plot.title = element_text(hjust = 0.5)) +
    theme( axis.text.y = element_text(size = 8)) 

ggsave("./../local/panels/Final/Supplementary/1/A.PBMC5K_Pearson_correlation.r1.pdf" , width = 20/3, height = 29/3, units = 'cm')

```

#### Predicted vs measured ADT scatter plot

```{r}
my_pal <- c("#E7E7E0","#A2A187", "#525240", "#03878F", "#F2B531","#ED5958","#68C6A4", "#113245")
PBMC2 <- filter(PBMC, gene %in% c("CD19","CD3","CD14","CD56"))
ggplot(PBMC2, aes(x=predicted_sclinear, y=real, col=cell_type_2)) + geom_point(alpha = 0.8, size=0.5) + facet_wrap(~gene, scales = "free") +
  scale_color_manual(values = my_pal[5:8]) + theme_classic2() + theme(legend.title = element_blank()) +
  geom_smooth(method=lm, se=FALSE, col=my_pal[2], alpha = 0.5) + geom_rug() +
  xlab("ScLinear - Predicted") + ylab("Real")

ggsave("./../local/panels/Final/Supplementary/1/B.pbmc5k_Markers.pdf", width = 20/3*2, height = 29/3, units = "cm")
```



### feature impact analysis PBMC5K

```{r}
if(FALSE){
  pbmc5k <- readRDS("./../local/PBMC5K_predicted.rds")
  
  pipe <- create_adt_predictor()
  pipe <- load_pretrained_model(pipe, model = "all")
  
  feature_importance <- function(pipe, gexp, slot = "counts", normalize = TRUE){
      gexp_matrix <- Seurat::GetAssayData(gexp, slot = slot)
    
      if(normalize){
      ## normalize data GEX
      sce <- SingleCellExperiment::SingleCellExperiment(list(counts = gexp_matrix))
      clusters <- scran::quickCluster(sce)
      sce <- scran::computeSumFactors(sce, clusters=clusters)
      sce <- scuttle::logNormCounts(sce, pseudo.count = 1, center.size.factors = FALSE, log = FALSE)
      gexp_matrix <- sce@assays@data@listData[["normcounts"]]
      gexp_matrix <- base::log1p(gexp_matrix)
    }
    gexp_matrix <- Matrix::t(gexp_matrix)
    gexp_matrix_py <- reticulate::r_to_py(as.matrix(gexp_matrix))
    feature_imp <- pipe$feature_importance(gexp_matrix_py, gex_names = colnames(gexp_matrix))
    colnames(feature_imp) <- pipe$gex_names$to_list()
    rownames(feature_imp) <- pipe$adt_names$to_list()
    
    return(feature_imp)
  }
  
  fi <- feature_importance(pipe, pbmc5k@assays$RNA, slot = "counts", normalize = TRUE)
  
  write.table(fi, "./../local/PBMC5K/feature_importance_pbmc5k.txt", sep = "\t", row.names = TRUE, col.names = TRUE, quote = FALSE)
  saveRDS(fi, "./../local/PBMC5K/feature_importance_pbmc5k.rds")
}
```

### Drop out simulation

```{r, fig.width=20/3*2, fig.height=29/3}
set.seed(42)
obj <-  readRDS("./../local/PBMC5K_prepared2.rds")
df <- GetAssayData(obj, assay = "RNA", slot = "counts")
index <- which(df != 0)
drops <- matrix(nrow = nrow(df), ncol = ncol(df), data = 1)
drops[index] <- 0
R <- nrow(df)
C <- ncol(df)
drop_rate <- length(which(drops == 1))/(R*C)
print(paste0("Initial dropout rate: ", drop_rate))
dropout_data_list <- list()

while(drop_rate < 0.99){
    index <- which(drops == 0)
    
    new_drops <- rbinom(length(index), 1, 0.1)
    
    drops[index[which(new_drops == 1)]] <- 1
    drop_rate <- length(which(drops == 1))/(R*C)
    print(paste0("New dropout: ", drop_rate))
    df_drop <- df
    df_drop[which(drops == 1)] <- 0
    dropout_data_list[[as.character(drop_rate)]] <- df_drop
}    

dropout_levels <- names(dropout_data_list)
for(i in 1:length(dropout_data_list)){
  check_df <- dropout_data_list[[dropout_levels[i]]]
  print(length(which(check_df == 0))/(R*C))
}

saveRDS(dropout_data_list, "./../local/pbmc5k_dropout_list.rds")
```




### predict PBMC5K with scLinear for drop out
```{r}
get_dropout_rate <- function(object){
  df <- GetAssayData(object, assay = "RNA",  slot = "counts")
  index <- which(df != 0)
  drops <- matrix(nrow = nrow(df), ncol = ncol(df), data = 1)
  drops[index] <- 0
  R <- nrow(df)
  C <- ncol(df)
  drop_rate <- length(which(drops == 1))/(R*C)
  return(drop_rate)
}

get_dropout_res <- function(pipe,object_test , input_type){
  do_rate <- get_dropout_rate(object_test)
  predicted_assay <- adt_predict(pipe = pipe, gexp = object_test@assays[["RNA"]], normalize = TRUE, slot = "counts")
  object_test[["predicted_adt"]] <- predicted_assay

  adt_real <- as.matrix(object_test@assays[["ADT"]]@data)
  adt_real <- adt_real %>% as.data.frame() %>% rownames_to_column("gene") %>% pivot_longer(!gene,names_to = "cell", values_to = "real")
  adt_predicted_sclinear <- as.matrix(object_test@assays[["predicted_adt"]]@data)
  adt_predicted_sclinear <- adt_predicted_sclinear %>% as.data.frame() %>% rownames_to_column("gene") %>% pivot_longer(!gene,names_to = "cell", values_to = "predicted_adt")
  
  
  meta <- object_test@meta.data %>% rownames_to_column("cell")
  
  bit_table <- adt_real %>% full_join(adt_predicted_sclinear, by = c("gene", "cell")) %>% full_join(meta, by = c("cell")) %>% mutate(type = input_type, dropout = do_rate)
  
  
  df <- bit_table %>% dplyr::select(cell, gene, real, predicted_adt, cell_type_2, type, dropout) %>% na.omit() %>% group_by(cell)
  
  return(df)
}


pbmc5k <- readRDS("./../local/PBMC5K_prepared2.rds")
## load pretrained predictor model scLinear
pipe <- create_adt_predictor()
pipe <- load_pretrained_model(pipe, model = "all")


dropout_res_list <- list()
dropout_res_list[["original"]] <- get_dropout_res(pipe, pbmc5k, "original")


dropout_data_list <- readRDS("./../local/pbmc5k_dropout_list.rds")

for(i in names(dropout_data_list)){
  print(i)
  obj <- pbmc5k
  new_assay <- Seurat::CreateAssayObject(counts = dropout_data_list[[i]])
  obj[["RNA"]] <- new_assay
  dropout_res_list[[i]] <- get_dropout_res(pipe, obj, "added_dropout")
  rm(obj)
  gc()
}

dropout_res <- do.call(rbind, dropout_res_list)

saveRDS(dropout_res, "./../local/dropout_res_pbmc5k.rds")

```


```{r,  fig.width=20/2, fig.height=29/2}
pbmc5k <- readRDS("./../local/PBMC5K_predicted.rds")

my_pal <- c("#525240", "#03878F")
dropout_res <- readRDS("./../local/dropout_res_pbmc5k.rds")


DF <- dropout_res%>% group_by(cell, dropout, type) %>% summarise(Pearson = cor(real, predicted_adt))
DF$Pearson <- as.numeric(DF$Pearson )

DF$type [!(DF$type == "original")]<- "added_dropout"

pos <- position_jitter(width = 0, height = 0, seed = 6)
p <- ggplot(DF, aes(x = dropout, y = Pearson, color = type, group = dropout)) +
  geom_boxplot(show.legend = FALSE,  outlier.size = 0.2) + theme_bw() +
  #geom_jitter(position=pos, size = 0.8) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  scale_fill_manual(values = my_pal) +
  ylab("Pearson\n(Real vs ScLinear)") + xlab("") +
  theme(legend.position = "none") +
   scale_color_manual(values = c(my_pal)) + scale_fill_manual(values = c(my_pal))  +
  theme(legend.position = "none") +
  theme(legend.title = element_blank()) +
  theme(legend.text = element_text(size = 8)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ylab("Pearson") +
  xlab("Dropout rate") + ggtitle("PBMC5K")

p

#ggsave(plot = p, "./../local/panels/Final/Main/2/B.PBMC5K_Dropout_boxplot.r1.pdf", width = 20/2, height = 29/3, units = 'cm')
```










```{r}
# pbmc5k <- readRDS("./../local/PBMC5K_prepared2.rds")
# 
# ## load pretrained predictor model scLinear
# pipe <- create_adt_predictor()
# pipe <- load_pretrained_model(pipe, model = "all")
# 
# 
# dropout_res <- NULL
# ## add results without noise
# eval_res <- evaluate_predictor(pipe, pbmc5k@assays$RNA, pbmc5k@assays$ADT)
# df <- GetAssayData(pbmc5k, assay = "RNA", slot = "counts")
# index <- which(df != 0)
# drops <- matrix(nrow = nrow(df), ncol = ncol(df), data = 1)
# drops[index] <- 0
# R <- nrow(df)
# C <- ncol(df)
# drop_rate <- length(which(drops == 1))/(R*C)
# dropout_res <- rbind(dropout_res, data.frame(dropout = drop_rate, RMSE= eval_res$RMSE, Pearson = eval_res$Pearson, Spearman = eval_res$Spearman, type = "original"))
# rm(eval_res, R, C, index, df, drops)
# gc()
# 
# dropout_data_list <- readRDS("./../local/pbmc5k_dropout_list.rds")
# for(i in names(dropout_data_list)){
#   print(i)
#   obj <- pbmc5k
#   obj@assays$RNA <- Seurat::CreateAssayObject(counts = dropout_data_list[[i]])
#   eval_res <- evaluate_predictor(pipe, obj@assays$RNA, obj@assays$ADT)
#   dropout_res <- rbind(dropout_res, data.frame(dropout = i, RMSE= eval_res$RMSE, Pearson = eval_res$Pearson, Spearman = eval_res$Spearman, type = "added_noise"))
#   rm(eval_res)
# }
# 
# saveRDS(dropout_res, "./../local/dropout_res_pbmc5k.rds")

```


```{r}
# my_pal <- c("#525240", "#03878F")
# 
# dropout_res <- readRDS("./../local/dropout_res_pbmc5k.rds")
# 
# dropout_res$dropout <- as.numeric(dropout_res$dropout )
# p <- ggplot(dropout_res, aes(x=dropout, y=Pearson, col=type)) + geom_point(size=2) + theme_classic2() + 
#   scale_color_manual(values = c(my_pal)) + scale_fill_manual(values = c(my_pal)) +
#   theme(legend.position = "none") +
#   theme(legend.title = element_blank()) +
#   theme(legend.text = element_text(size = 8)) +
#   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
#   xlim(c(NA,1.01)) +
#   scale_x_continuous(labels = scales::number_format(accuracy = 0.01, decimal.mark = '.'),
#                      breaks = seq(round(min(dropout_res$dropout), 2), 1, by = 0.01)) +
#   xlab("Dropout rate") +
#   ylab("Pearson")
#   
# p
# 
# ggsave(plot = p, "./../local/panels/Final/Main/2/B.PBMC5K_Dropout.r1.pdf", width = 20/2, height = 29/4, units = 'cm')
```

```{r}

sessionInfo()

```

