---
title: "Analysis"
author: "Daniel Hanhart"
date: "3/16/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(scLinear)
library(tidyverse)
library(ggplot2)
library(Seurat)
library(svglite)
library(Metrics)
library(pals)
library(ggpubr)


set.seed(42)
```

## PBMC10K

### Create Seurat object from raw data

```{r}
## data from: https://satijalab.org/seurat/archive/v3.2/multimodal_vignette.html
# create seurat object from pbmc10k data

## Some of the protein names differ from the ones used in the NeurIPS data (CD8a -> CD8, PD-1 -> CD279). Create name mapping."
map_names <- data.frame(
	pbmc10k = c("CD3", "CD4", "CD8a", "CD14", "CD15", "CD16", "CD56", "CD19", "CD25", "CD45RA", "CD45RO", "PD-1", "TIGIT", "CD127", "IgG2a", "IgG1", "IgG2b"),
	neurips = c("CD3", "CD4", "CD8", "CD14", "CD15", "CD16", "CD56", "CD19", "CD25", "CD45RA", "CD45RO", "CD279", "TIGIT", "CD127", "IgG2a", "IgG1", "IgG2b")
)


pbmc10k.data <- Seurat::Read10X_h5("./../local/PBMC/pbmc_10k_protein_v3_filtered_feature_bc_matrix.h5")
rownames(x = pbmc10k.data[["Antibody Capture"]]) <- gsub(pattern = "_[control_]*TotalSeqB", replacement = "",
                                                           x = rownames(x = pbmc10k.data[["Antibody Capture"]]))
  
rownames(x = pbmc10k.data[["Antibody Capture"]]) <- map_names$neurips[ match(rownames(x = pbmc10k.data[["Antibody Capture"]]), map_names$pbmc10k)]



pbmc10k <- Seurat::CreateSeuratObject(counts = pbmc10k.data[["Gene Expression"]], min.cells = 0, min.features = 0)
pbmc10k[["ADT"]] <- Seurat::CreateAssayObject(pbmc10k.data[["Antibody Capture"]][, colnames(x = pbmc10k)])
Seurat::DefaultAssay(pbmc10k) <- "RNA"

pbmc10k$mito_percent <- Seurat::PercentageFeatureSet(object = pbmc10k, pattern = "^MT-")
pbmc10k$ribo_percent <- Seurat::PercentageFeatureSet(object = pbmc10k, pattern = "^RP[SL]")

saveRDS(pbmc10k, "./../local/pbmc10k_filtered.rds")
rm(pbmc10k.data)
gc()
```


### Preprocess PBMC10K data

```{r}
if(!exists("pbmc10k")){pbmc10k <- readRDS("./../local/pbmc10k_filtered.rds")}

## Perform basc preprocessing steps including: lognormalization, removal of doublets, removal of low quality cells, clustering, cell-type annotation
pbmc10k <- scLinear::prepare_data(pbmc10k,
                                   remove_doublets = TRUE,
                                   low_qc_cell_removal = TRUE,
                                   anno_level = c(1,2,3,4),
                                   samples = NULL,
                                   integrate_data = FALSE,
                                   remove_empty_droplets = FALSE,
                                   lower = 100, FDR = 0.01,
                                   annotation_selfCluster = TRUE,
                                   resolution = 0.8,
                                   seed = 42)

DimPlot(pbmc10k, group.by = "cell_type_2")


saveRDS(pbmc10k, "./../local/PBMC10K_prepared.rds")
```
### Take a look into the ADT data
```{r}
if(!exists("pbmc10k")){pbmc10k <- readRDS("./../local/PBMC10K_prepared.rds")}


iso_features <- c("IgG2a", "IgG1", "IgG2b")
all_features <- rownames(pbmc10k@assays$ADT)
iso_count <- colSums(x = GetAssayData(object = pbmc10k, assay = "ADT", slot = "counts")[iso_features, , drop = FALSE])
total_counts_ADT <- colSums(x = GetAssayData(object = pbmc10k, assay = "ADT", slot = "counts")[all_features, , drop = FALSE])

plot(pbmc10k$nCount_ADT, pbmc10k$nFeature_ADT)

hist(total_counts_ADT, breaks = 100)
hist(iso_count, breaks = 100)

## Normalize ADT data
pbmc10k <- Seurat::NormalizeData(pbmc10k, normalization.method = "CLR", margin = 2, assay = "ADT")

saveRDS(pbmc10k, "./../local/PBMC10K_prepared.rds")
```



### UMAP

```{r}
if(!exists("pbmc10k")){pbmc10k <- readRDS("./../local/PBMC10K_prepared.rds")}

p <- DimPlot(pbmc10k, group.by = "cell_type_2", pt.size = 0.05) + ggtitle("Cell types") +
  scale_color_manual(values = c("#BE0032","#008856","#0067A5", "#F3C300")) + theme_bw()
p
ggsave(filename = "./../local/figures/umap_pbmc10k.pdf", plot = p, width = 9, height = 6, units = "cm")
rm(p)
```

### predict PBMC10K with scLinear


```{r}
if(!exists("pbmc10k")){pbmc10k <- readRDS("./../local/PBMC10K_prepared.rds")}

## load pretrained predictor model scLinear
pipe <- create_adt_predictor()
pipe <- load_pretrained_model(pipe, model = "all")
assay_predicted <- adt_predict(pipe, pbmc10k@assays$RNA, normalize = TRUE)

eval_res <- evaluate_predictor(pipe, pbmc10k@assays$RNA, pbmc10k@assays$ADT)

pbmc10k[["predicted_adt_sclinear"]] <- assay_predicted

saveRDS(pbmc10k, "./../local/PBMC10K_predicted.rds")
rm(assay_predicted, eval_res,pipe)
gc()
```



```{r}
if(!exists("pbmc10k")){pbmc10k <- readRDS("./../local/PBMC10K_predicted.rds")}
pipe <- create_adt_predictor()
pipe$load("./../local/trained_predicors/ADTPredictorKRREnsemble_neuripstrain_alltypes.joblib")

assay_predicted <- adt_predict(pipe, pbmc10k@assays$RNA, normalize = TRUE)

eval_res <- evaluate_predictor(pipe, pbmc10k@assays$RNA, pbmc10k@assays$ADT)

pbmc10k[["predicted_adt_krr"]] <- assay_predicted


saveRDS(pbmc10k, "./../local/PBMC10K_predicted.rds")
rm(assay_predicted, eval_res,pipe)
gc()
```

`

### bit table (real vs preducted)

```{r}
if(!exists("pbmc10k")){pbmc10k <- readRDS("./../local/PBMC10K_predicted.rds")}

  adt_real <- as.matrix(pbmc10k@assays[["ADT"]]@data)
  adt_real <- adt_real %>% as.data.frame() %>% rownames_to_column("gene") %>% pivot_longer(!gene,names_to = "cell", values_to = "real")
  adt_predicted_sclinear <- as.matrix(pbmc10k@assays[["predicted_adt_sclinear"]]@data)
  adt_predicted_sclinear <- adt_predicted_sclinear %>% as.data.frame() %>% rownames_to_column("gene") %>% pivot_longer(!gene,names_to = "cell", values_to = "predicted_sclinear")
  adt_predicted_krr <- as.matrix(pbmc10k@assays[["predicted_adt_krr"]]@data)
  adt_predicted_krr <- adt_predicted_krr %>% as.data.frame() %>% rownames_to_column("gene") %>% pivot_longer(!gene,names_to = "cell", values_to = "predicted_krr")
  
  
  meta <- pbmc10k@meta.data %>% rownames_to_column("cell") %>% dplyr::select("cell","cell_type_1","cell_type_2","cell_type_3","cell_type_4")
  
  
  DF <- adt_real %>% full_join(adt_predicted_sclinear, by = c("gene", "cell")) %>%  full_join(adt_predicted_krr, by = c("gene", "cell"))  %>% full_join(meta, by = c("cell"))
  
  write.table(DF, file = "./../local/PBMC/bit_table_pbmc10k.csv", sep = ",", col.names = TRUE, row.names = FALSE)
  #DF_sum <- DF %>% na.omit() %>% mutate(cell_type_2 = factor(cell_type_2)) %>% group_by(cell_type_2)  %>% summarize(pearson_sclinear = cor(real, adt_predicted_sclinear, method = "pearson"), spearman_sclinear = cor(real, adt_predicted_sclinear, method = "spearman"))

  ## calculate per cell cor, then take mean
   #d <- DF %>% na.omit() %>% group_by(cell)  %>% summarize(pearson = cor(real, predicted_sclinear, method = "pearson"), spearman = cor(real, predicted_sclinear, method = "spearman")) %>% ungroup() %>% summarize(pearson = mean(pearson), spearman = mean(spearman))
  
  
  d <- DF %>% na.omit() %>% group_by(gene)  %>% summarize(pearson = cor(real, predicted_sclinear, method = "pearson"), spearman = cor(real, predicted_sclinear, method = "spearman")) #%>% ungroup() %>% summarize(pearson = mean(pearson), spearman = mean(spearman))
  
```




### Visualize by gene / cell type

```{r}
a
df <- DF %>% na.omit()

cor_label <- df %>% group_by(gene) %>% summarise(cor = round(cor(predicted_sclinear, real), digits = 2), slope = round(coef(lm(predicted_sclinear ~ real))[[2]], digits = 2))
gene_factors <- cor_label %>% arrange(desc(cor))  %>% pull("gene") %>% unique()

df$gene <- factor(df$gene, levels=gene_factors) 
df <- df %>% arrange(desc(gene))

ggplot(df, aes(x = real, y = predicted_sclinear, color = gene, legend = gene)) + 
  geom_point(size = 0.01) +
  geom_smooth(method = "lm", show.legend = FALSE, se = FALSE) + 
  theme_bw() + 
  guides(color = guide_legend( shape = 15), fill = guide_legend( shape = 15)) +
  scale_colour_manual(values = kelly()[3:length(kelly())]) + 
  theme(text = element_text(size = 10),
          axis.text.x = element_text(size = 10),
          axis.text.y = element_text(size = 10),
          legend.key = element_rect(color = "black"),
          legend.key.height = unit(0.3,"points"),
          legend.key.width = unit(0.3,"points")) +
  guides(color = guide_legend(override.aes = list(size=6, shape = 15))) +
  labs(fill = "Gene", color = "Gene")
```




################################################################################





```{r}

pbmc10k <- readRDS("./../local/PBMC10K_prepared.rds")


t_cells <- pbmc10k %>% base::subset(subset = cell_type == "T")
b_cells <- pbmc10k %>% base::subset(subset = cell_type == "B")
nk_cells <- pbmc10k %>% base::subset(subset = cell_type == "NK cells")
monocytes <- pbmc10k %>% base::subset(subset = cell_type == "Monocyte")

pipe <- create_adt_predictor()

## for all
res <- list()
pipe <- load_pretrained_model(pipe, model = "all")
pipe$gex_preprocessor$do_log1p <- FALSE
res[["T cells"]] <- evaluate_predictor(pipe, t_cells@assays$RNA, t_cells@assays$ADT, normalize = TRUE)
res[["B cells"]] <- evaluate_predictor(pipe, b_cells@assays$RNA, b_cells@assays$ADT, normalize = TRUE)
res[["NK cells"]] <- evaluate_predictor(pipe, nk_cells@assays$RNA, nk_cells@assays$ADT, normalize = TRUE)
res[["Monocytes"]] <- evaluate_predictor(pipe, monocytes@assays$RNA, monocytes@assays$ADT, normalize = TRUE)
res_all <- do.call( rbind, res)
colnames(res_all) <- c("RMSE", "Pearson", "Spearman")
res_all <- cbind(res_all, model = "all")
res_all <- res_all %>% as.data.frame() %>% rownames_to_column("name")


##bcell model
res <- list()
pipe <- load_pretrained_model(pipe, model = "bcell")
pipe$gex_preprocessor$do_log1p <- FALSE
res[["T cells"]] <- evaluate_predictor(pipe, t_cells@assays$RNA, t_cells@assays$ADT, normalize = TRUE)
res[["B cells"]] <- evaluate_predictor(pipe, b_cells@assays$RNA, b_cells@assays$ADT, normalize = TRUE)
res[["NK cells"]] <- evaluate_predictor(pipe, nk_cells@assays$RNA, nk_cells@assays$ADT, normalize = TRUE)
res[["Monocytes"]] <- evaluate_predictor(pipe, monocytes@assays$RNA, monocytes@assays$ADT, normalize = TRUE)
res_bcell <- do.call( rbind, res)
colnames(res_bcell) <- c("RMSE", "Pearson", "Spearman")
res_bcell <- cbind(res_bcell, model = "bcell")
res_bcell <- res_bcell %>% as.data.frame() %>% rownames_to_column("name")


##nkcell model
res <- list()
pipe <- load_pretrained_model(pipe, model = "nkcell")
pipe$gex_preprocessor$do_log1p <- FALSE
res[["T cells"]] <- evaluate_predictor(pipe, t_cells@assays$RNA, t_cells@assays$ADT, normalize = TRUE)
res[["B cells"]] <- evaluate_predictor(pipe, b_cells@assays$RNA, b_cells@assays$ADT, normalize = TRUE)
res[["NK cells"]] <- evaluate_predictor(pipe, nk_cells@assays$RNA, nk_cells@assays$ADT, normalize = TRUE)
res[["Monocytes"]] <- evaluate_predictor(pipe, monocytes@assays$RNA, monocytes@assays$ADT, normalize = TRUE)
res_nkcell <- do.call( rbind, res)
colnames(res_nkcell) <- c("RMSE", "Pearson", "Spearman")
res_nkcell <- cbind(res_nkcell, model = "nkcell")
res_nkcell <- res_nkcell %>% as.data.frame() %>% rownames_to_column("name")


##tcell model
res <- list()
pipe <- load_pretrained_model(pipe, model = "tcell")
pipe$gex_preprocessor$do_log1p <- FALSE
res[["T cells"]] <- evaluate_predictor(pipe, t_cells@assays$RNA, t_cells@assays$ADT, normalize = TRUE)
res[["B cells"]] <- evaluate_predictor(pipe, b_cells@assays$RNA, b_cells@assays$ADT, normalize = TRUE)
res[["NK cells"]] <- evaluate_predictor(pipe, nk_cells@assays$RNA, nk_cells@assays$ADT, normalize = TRUE)
res[["Monocytes"]] <- evaluate_predictor(pipe, monocytes@assays$RNA, monocytes@assays$ADT, normalize = TRUE)
res_tcell <- do.call( rbind, res)

colnames(res_tcell) <- c("RMSE", "Pearson", "Spearman")
res_tcell <- cbind(res_tcell, model = "tcell")
res_tcell <- res_tcell %>% as.data.frame() %>% rownames_to_column("name")


res <- rbind(res_all, res_bcell, res_nkcell, res_tcell)

saveRDS(res, "./../local/results.rds")

```

### UMAP

```{r}
library(pals)
kelly()
p <- DimPlot(pbmc10k, group.by = "cell_type") + ggtitle("Cell types") +
  scale_color_manual(values = c("#BE0032","#008856","#0067A5", "#F3C300")) + theme_bw()
p

ggsave(filename = "./../local/umap.svg", plot = p)

# red "#BE0032"
# yellow "#F3C300"
#blue "#0067A5"
#green "#008856"

```

```{r}
res <- readRDS("./../local/results.rds")

res$name <-  unlist(res$name)
res$RMSE <-  unlist(res$RMSE)
res$Pearson <-  unlist(res$Pearson)
res$Spearman <-  unlist(res$Spearman)
res$model <-  unlist(res$model)



DF <- res %>% as.data.frame()
DF <- DF %>% pivot_longer(values_to = "value", cols = -c(name, model), names_to = "measure")
DF$measure <- factor(DF$measure, levels = c("RMSE", "Pearson", "Spearman"))
## dummy variable to change axis range
dummy <- data.frame(measure = c("RMSE", "RMSE", "Pearson", "Pearson", "Spearman", "Spearman") , value = c(range(DF %>% filter(measure == "RMSE") %>% pull("value") ), min(DF$value), 1, min(DF$value), 1), model = c("all","all","all","all","all","all"), name = c("T cells","T cells","T cells","T cells","T cells","T cells"))
dummy$measure <- factor(dummy$measure, levels = c("RMSE", "Pearson", "Spearman"))

p <- ggplot(DF, aes(x = model, y = value, fill = name, group_by = measure)) +
  geom_bar(stat="identity", position=position_dodge( width = 0.9)) +
  theme_bw() +
  geom_blank(data = dummy) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        text = element_text(size = 30)) +
  facet_grid(.~ measure, scales = "free_y") + scale_fill_manual(values = c("#BE0032","#008856","#0067A5","#F3C300")) +
  labs()
p

ggsave(filename = "./../local/results.svg", plot = p, height = 10, width = 10)
ggsave(filename = "./../local/results.pdf", plot = p, height = 10, width = 10)


```


### predicted vs test scatter plot

```{r}
#### investigate difference in spearman, pearson correlation bcell
pipe <- create_adt_predictor()

#### bcell
pipe <- load_pretrained_model(pipe, model = "bcell")
pipe$gex_preprocessor$do_log1p <- FALSE
evaluate_predictor(pipe, b_cells@assays$RNA, b_cells@assays$ADT, normalize = TRUE)

assay_predicted <- adt_predict(pipe, b_cells@assays$RNA)
assay_test <- b_cells@assays$ADT

p <- predicted_vs_test_plot(assay_predicted, assay_test)
p <- p + ggtitle("B cells, B cell model")
p
ggsave(filename = "./../local/test_vs_pred_Bcells_modelB.svg", plot = p)


#### bcell full model
pipe <- load_pretrained_model(pipe, model = "all")
pipe$gex_preprocessor$do_log1p <- FALSE
evaluate_predictor(pipe, b_cells@assays$RNA, b_cells@assays$ADT, normalize = TRUE)

assay_predicted <- adt_predict(pipe, b_cells@assays$RNA)
assay_test <- b_cells@assays$ADT

p <- predicted_vs_test_plot(assay_predicted, assay_test)
p <- p + ggtitle("B cells, All cell model")
p
ggsave(filename = "./../local/test_vs_pred_Bcells_modelAll.svg", plot = p)



#### tcell
pipe <- load_pretrained_model(pipe, model = "tcell")
pipe$gex_preprocessor$do_log1p <- FALSE
evaluate_predictor(pipe, t_cells@assays$RNA, t_cells@assays$ADT, normalize = TRUE)

assay_predicted <- adt_predict(pipe, t_cells@assays$RNA)
assay_test <- t_cells@assays$ADT

p <- predicted_vs_test_plot(assay_predicted, assay_test)
p <- p + ggtitle("T cells, T cell model")
p
ggsave(filename = "./../local/test_vs_pred_Tcells_modelT.svg", plot = p)


#### nkcells
pipe <- load_pretrained_model(pipe, model = "nkcell")
pipe$gex_preprocessor$do_log1p <- FALSE
evaluate_predictor(pipe, nk_cells@assays$RNA, nk_cells@assays$ADT, normalize = TRUE)

assay_predicted <- adt_predict(pipe, nk_cells@assays$RNA)
assay_test <- nk_cells@assays$ADT

p <- predicted_vs_test_plot(assay_predicted, assay_test)
p <- p + ggtitle("NK cells, NK cell model")
p
ggsave(filename = "./../local/test_vs_pred_NKcells_modelNK.svg", plot = p)


#### all cells full model
pipe <- load_pretrained_model(pipe, model = "all")
pipe$gex_preprocessor$do_log1p <- FALSE
evaluate_predictor(pipe, pbmc10k@assays$RNA, pbmc10k@assays$ADT, normalize = TRUE)

assay_predicted <- adt_predict(pipe, pbmc10k@assays$RNA)
assay_test <- pbmc10k@assays$ADT

p <- predicted_vs_test_plot(assay_predicted, assay_test)
p <- p + ggtitle("All cells, All cell model")
p
ggsave(filename = "./../local/test_vs_pred_Allcells_modelAll.svg", plot = p)

#### monocytes full model
pipe <- load_pretrained_model(pipe, model = "all")
pipe$gex_preprocessor$do_log1p <- FALSE
evaluate_predictor(pipe, monocytes@assays$RNA, monocytes@assays$ADT, normalize = TRUE)

assay_predicted <- adt_predict(pipe, monocytes@assays$RNA)
assay_test <- monocytes@assays$ADT

p <- predicted_vs_test_plot(assay_predicted, assay_test)
p <- p + ggtitle("Monocytes, All cell model")
p


```



```{r}

pbmc10k <- readRDS("./../local/PBMC10K_prepared.rds")

t_cells <- pbmc10k %>% base::subset(subset = cell_type == "T")


## create train and test set
set.seed(42)
indx <- sample(1:length(colnames(t_cells)), size = length(colnames(t_cells)), replace = FALSE)
t_cells_train <- t_cells[,indx[1:2000]]
t_cells_test <- t_cells[,indx[2001:length(colnames(t_cells))]]

## create predictor
pipe <- create_adt_predictor()

pipe <- fit_predictor(pipe = pipe, gexp_train = t_cells_train@assays[["RNA"]],
              adt_train = t_cells_train@assays[["ADT"]],
              normalize = TRUE)



evaluate_predictor(pipe = pipe,
                  gexp_test = t_cells_test@assays[["RNA"]],
                  adt_test = t_cells_test@assays[["ADT"]],
                  normalize = TRUE)


t_cells_test@assays[["predicted_ADT"]] <-  adt_predict(pipe = pipe, gexp = t_cells_test@assays[["RNA"]], normalize = TRUE)


assay_predicted <- t_cells_test@assays[["predicted_ADT"]]
assay_test <- t_cells_test@assays[["ADT"]]

p <- predicted_vs_test_plot(assay_predicted, assay_test)
p <- p + ggtitle("T cells, T cell model")
p


################################################################################


pbmc10k <- readRDS("./../local/PBMC10K_prepared.rds")



## create train and test set
set.seed(42)
indx <- sample(1:length(colnames(pbmc10k)), size = length(colnames(pbmc10k)), replace = FALSE)
pbmc10k_train <- pbmc10k[,indx[1:5000]]
pbmc10k_test <- pbmc10k[,indx[5001:length(colnames(pbmc10k))]]

## create predictor
pipe <- create_adt_predictor()

pipe <- fit_predictor(pipe = pipe, gexp_train = pbmc10k_train@assays[["RNA"]],
              adt_train = pbmc10k_train@assays[["ADT"]],
              normalize = TRUE)



evaluate_predictor(pipe = pipe,
                  gexp_test = pbmc10k_test@assays[["RNA"]],
                  adt_test = pbmc10k_test@assays[["ADT"]],
                  normalize = TRUE)


pbmc10k_test@assays[["predicted_ADT"]] <-  adt_predict(pipe = pipe, gexp = pbmc10k_test@assays[["RNA"]], normalize = TRUE)


assay_predicted <- pbmc10k_test@assays[["predicted_ADT"]]
assay_test <- pbmc10k_test@assays[["ADT"]]

p <- predicted_vs_test_plot(assay_predicted, assay_test)
p <- p + ggtitle("all cells, all cell model")
p


```





## KRR

```{r}
# pbmc10k <- readRDS("./../local/PBMC10K_prepared.rds")
# 
# pipe <- create_adt_predictor()
# 
# pipe$load("./../local/ADTPredictorKRREnsemble_neuripstrain_alltypes.joblib")
# pipe$gex_preprocessor$do_log1p <- FALSE
# evaluate_predictor(pipe = pipe,
#                   gexp_test = pbmc10k@assays[["RNA"]],
#                   adt_test = pbmc10k@assays[["ADT"]],
#                   normalize = TRUE)
# 
# 





pbmc10k <- readRDS("./../local/PBMC10K_prepared.rds")


t_cells <- pbmc10k %>% base::subset(subset = cell_type == "T")
b_cells <- pbmc10k %>% base::subset(subset = cell_type == "B")
nk_cells <- pbmc10k %>% base::subset(subset = cell_type == "NK cells")


pipe <- create_adt_predictor()

## for all
res <- list()
pipe$load("./../local/ADTPredictorKRREnsemble_neuripstrain_alltypes.joblib")
pipe$gex_preprocessor$do_log1p <- FALSE
res[["t_cells"]] <- evaluate_predictor(pipe, t_cells@assays$RNA, t_cells@assays$ADT, normalize = TRUE)
res[["b_cells"]] <- evaluate_predictor(pipe, b_cells@assays$RNA, b_cells@assays$ADT, normalize = TRUE)
res[["nk_cells"]] <- evaluate_predictor(pipe, nk_cells@assays$RNA, nk_cells@assays$ADT, normalize = TRUE)
res_all <- do.call( rbind, res)
colnames(res_all) <- c("RMSE", "Pearson", "Spearman")
res_all <- cbind(res_all, model = "all")
res_all <- res_all %>% as.data.frame() %>% rownames_to_column("name")

res <- res_all

res$name <-  unlist(res$name)
res$RMSE <-  unlist(res$RMSE)
res$Pearson <-  unlist(res$Pearson)
res$Spearman <-  unlist(res$Spearman)
res$model <-  unlist(res$model)

DF <- res %>% as.data.frame()
DF <- DF %>% pivot_longer(values_to = "value", cols = -c(name, model), names_to = "measure")
DF$measure <- factor(DF$measure, levels = c("RMSE", "Pearson", "Spearman"))
## dummy variable to change axis range
dummy <- data.frame(measure = c("RMSE", "RMSE", "Pearson", "Pearson", "Spearman", "Spearman") , value = c(range(DF %>% filter(measure == "RMSE") %>% pull("value") ), min(DF$value), 1, min(DF$value), 1), model = c("all","all","all","all","all","all"), name = c("t_cells","t_cells","t_cells","t_cells","t_cells","t_cells"))
dummy$measure <- factor(dummy$measure, levels = c("RMSE", "Pearson", "Spearman"))

p <- ggplot(DF, aes(x = model, y = value, fill = name, group_by = measure)) +
  geom_bar(stat="identity", position=position_dodge()) +
  theme_bw() +
  geom_blank(data = dummy) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  facet_wrap(.~ measure, scales = "free_y") + scale_fill_manual(values = c("#BE0032","#0067A5","#F3C300"))
p

ggsave(filename = "./../local/KRREnsemble.svg", plot = p)


```

## Create Plots for Paper

### Prediction comparison

```{r}


res <- readRDS("./../local/results.rds")

res$name <-  unlist(res$name)
res$RMSE <-  unlist(res$RMSE)
res$Pearson <-  unlist(res$Pearson)
res$Spearman <-  unlist(res$Spearman)
res$model <-  unlist(res$model)



DF <- res %>% as.data.frame()
DF <- DF %>% pivot_longer(values_to = "value", cols = -c(name, model), names_to = "measure")
DF$measure <- factor(DF$measure, levels = c("RMSE", "Pearson", "Spearman"))
## dummy variable to change axis range
dummy <- data.frame(measure = c("RMSE", "RMSE", "Pearson", "Pearson", "Spearman", "Spearman") , value = c(range(DF %>% filter(measure == "RMSE") %>% pull("value") ), min(DF$value), 1, min(DF$value), 1), model = c("all","all","all","all","all","all"), name = c("T cells","T cells","T cells","T cells","T cells","T cells"))
dummy$measure <- factor(dummy$measure, levels = c("RMSE", "Pearson", "Spearman"))

p <- ggplot(DF, aes(x = model, y = value, fill = name, group_by = measure)) +
  geom_bar(stat="identity", position=position_dodge(width = 0.7), width = 0.65) +
  theme_bw() +
  geom_blank(data = dummy) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        text = element_text(size = 30)) +
  facet_grid(.~ measure, scales = "free_y") + scale_fill_manual(values = c("#BE0032","#008856","#0067A5","#F3C300")) +
  labs()
p

ggsave(filename = "./../local/results.svg", plot = p, height = 10, width = 25)
#ggsave(filename = "./../local/results.pdf", plot = p, height = 10, width = 10)
```


### UMAP

```{r}
library(pals)
kelly()
p <- DimPlot(pbmc10k, group.by = "cell_type") + ggtitle("Cell types") +
  scale_color_manual(values = c("#BE0032","#008856","#0067A5", "#F3C300")) +
  theme_bw() +
  theme(text = element_text(size = 30)) +
  guides(colour = guide_legend(override.aes = list(size=6)))
p

ggsave(filename = "./../local/umap.svg", plot = p, height = 8, width = 10)





```


### Scatter plot full model

```{r}
#### all cells full model
pipe <- load_pretrained_model(pipe, model = "all")
pipe$gex_preprocessor$do_log1p <- FALSE
evaluate_predictor(pipe, pbmc10k@assays$RNA, pbmc10k@assays$ADT, normalize = TRUE)

assay_predicted <- adt_predict(pipe, pbmc10k@assays$RNA)
assay_test <- pbmc10k@assays$ADT

library(RColorBrewer)
p <- predicted_vs_test_plot(assay_predicted, assay_test) +
  theme(text = element_text(size = 40),axis.text.x = element_text(size = 10)) +
  scale_colour_manual(values = kelly()[3:length(kelly())]) +
  guides(colour = guide_legend(override.aes = list(size=8)))
p <- p + ggtitle("All cells, all cell types model")
p


ggsave(filename = "./../local/test_vs_pred_Allcells_modelAll.svg", plot = p, height = 15, width  = 20)


metadata <- pbmc10k@meta.data
p <- predicted_vs_test_highlight_plot(assay_predicted, assay_test, metadata, highlight = "B") +
  theme(text = element_text(size = 40),axis.text.x = element_text(size = 10)) +
  scale_colour_manual(values = kelly()[3:length(kelly())]) +
  guides(colour = guide_legend(override.aes = list(size=8)))
p <- p + ggtitle("All cells, all cell types model")
p
ggsave(filename = "./../local/test_vs_pred_Allcells_modelAll_Bhighlithed.svg", plot = p, height = 15, width  = 20)

```

### Scatter plot KRR model

```{r}

pbmc10k <- readRDS("./../local/PBMC10K_prepared.rds")

pipe <- create_adt_predictor()

## for all
pipe$load("./../local/ADTPredictorKRREnsemble_neuripstrain_alltypes.joblib")
pipe$gex_preprocessor$do_log1p <- FALSE

evaluate_predictor(pipe, pbmc10k@assays$RNA, pbmc10k@assays$ADT, normalize = TRUE)

assay_predicted <- adt_predict(pipe, pbmc10k@assays$RNA)
assay_test <- pbmc10k@assays$ADT
library(RColorBrewer)
p <- predicted_vs_test_plot(assay_predicted, assay_test) +
  theme(text = element_text(size = 40),axis.text.x = element_text(size = 10)) +
  scale_colour_manual(values = kelly()[3:length(kelly())]) +
  guides(colour = guide_legend(override.aes = list(size=8)))
p <- p + ggtitle("All cells, KRR model")
p


ggsave(filename = "./../local/test_vs_pred_Allcells_KRR.svg", plot = p, height = 15, width  = 20)


################################################################################
## b cells
b_cells <- pbmc10k %>% base::subset(subset = cell_type == "B")


assay_predicted <- adt_predict(pipe, b_cells@assays$RNA)
assay_test <- b_cells@assays$ADT
library(RColorBrewer)
p <- predicted_vs_test_plot(assay_predicted, assay_test) +
  theme(text = element_text(size = 40),axis.text.x = element_text(size = 10)) +
  scale_colour_manual(values = kelly()[3:length(kelly())]) +
  guides(colour = guide_legend(override.aes = list(size=8)))
p <- p + ggtitle("B cells, KRR model")
p


ggsave(filename = "./../local/test_vs_pred_Bcells_KRR.svg", plot = p, height = 15, width  = 20)




################################################################################



```





