---
title: "Train Models"
author: "Daniel Hanhart"
date: "10/9/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(reticulate)
library(scLinear)
library(tidyverse)
ad <- reticulate::import("anndata")
np <- reticulate::import("numpy")
```


## Load NeurIPS data


```{r}
## get cell types etc. from fully annotated data
bmmc_annotated <- ad$read_h5ad ("./../local/NeurIPS/annotated_data/openproblems_bmmc_cite_complete.h5ad")
metadata <- bmmc_annotated$obs %>% data.frame() %>% rownames_to_column("cell")

gex_train <- ad$read_h5ad ("./../local/NeurIPS/competition_data/openproblems_bmmc_cite_phase2_rna.censor_dataset.output_train_mod1.h5ad")
gex_test <- ad$read_h5ad ("./../local/NeurIPS/competition_data/openproblems_bmmc_cite_phase2_rna.censor_dataset.output_test_mod1.h5ad")
adt_train <- ad$read_h5ad ("./../local/NeurIPS/competition_data/openproblems_bmmc_cite_phase2_rna.censor_dataset.output_train_mod2.h5ad")
adt_test <- ad$read_h5ad ("./../local/NeurIPS/competition_data/openproblems_bmmc_cite_phase2_rna.censor_dataset.output_test_mod2.h5ad")

# gex
gex_train_r <- gex_train$X %>% Matrix::t()
rownames(gex_train_r) <- gex_train$var_names$to_list()
colnames(gex_train_r) <- gex_train$obs_names$to_list()
meta <- metadata[metadata$cell %in% colnames(gex_train_r),]
meta <- meta[match(colnames(gex_train_r), meta$cell),]
rownames(meta) <- NULL
meta <- meta %>% column_to_rownames("cell")
sobj_train <- Seurat::CreateSeuratObject(counts = gex_train_r, meta.data = meta, slot = "data")

# adt
adt_train_r <- adt_train$X %>% Matrix::t()
rownames(adt_train_r) <- adt_train$var_names$to_list()
colnames(adt_train_r) <- adt_train$obs_names$to_list()

if(all(colnames(adt_train_r) == colnames(sobj_train@assays$RNA))){
  adt_assay <- Seurat::CreateAssayObject(counts = adt_train_r, slot = "data")
  sobj_train[["ADT"]] <- adt_assay
}else{stop("Not the same order of cells")}




## for test set

# gex
gex_test_r <- gex_test$X %>% Matrix::t()
rownames(gex_test_r) <- gex_test$var_names$to_list()
colnames(gex_test_r) <- gex_test$obs_names$to_list()
meta <- metadata[metadata$cell %in% colnames(gex_test_r),]
meta <- meta[match(colnames(gex_test_r), meta$cell),]
rownames(meta) <- NULL
meta <- meta %>% column_to_rownames("cell")
sobj_test <- Seurat::CreateSeuratObject(counts = gex_test_r, meta.data = meta, slot = "data")

# adt
adt_test_r <- adt_test$X %>% Matrix::t()
rownames(adt_test_r) <- adt_test$var_names$to_list()
colnames(adt_test_r) <- adt_test$obs_names$to_list()

if(all(colnames(adt_test_r) == colnames(sobj_test@assays$RNA))){
  adt_assay <- Seurat::CreateAssayObject(counts = adt_test_r, slot = "data")
  sobj_test[["ADT"]] <- adt_assay
}else{stop("Not the same order of cells")}


saveRDS(sobj_train, "./../local/NeurIPS/neurips_train.rds")
saveRDS(sobj_test, "./../local/NeurIPS/neurips_test.rds")
```



### Analyse some NeurIPS data

```{r, fig.height = 20}
sobj_test <- readRDS("./../local/NeurIPS/neurips_test.rds")

## load pretrained predictor model scLinear
pipe <- create_adt_predictor()
pipe <- load_pretrained_model(pipe, model = "all")

assay_predicted <- adt_predict(pipe, sobj_test@assays$RNA, normalize = FALSE, slot = "data")
sobj_test[["predicted_adt_sclinear"]] <- assay_predicted

adt_real <- as.matrix(sobj_test@assays[["ADT"]]@data)
adt_real <- adt_real %>% as.data.frame() %>% rownames_to_column("gene") %>% pivot_longer(!gene,names_to = "cell", values_to = "real")
adt_predicted_sclinear <- as.matrix(sobj_test@assays[["predicted_adt_sclinear"]]@data)
adt_predicted_sclinear <- adt_predicted_sclinear %>% as.data.frame() %>% rownames_to_column("gene") %>% pivot_longer(!gene,names_to = "cell", values_to = "predicted_sclinear")


meta <- sobj_test@meta.data %>% rownames_to_column("cell")
## add borad cell types
{
meta$broad_cell_type <- NA
meta$broad_cell_type[meta$cell_type %in% c('CD4+ T naive', 'CD4+ T activated', 'CD4+ T activated integrinB7+', 'MAIT', 'CD8+ T naive', 'T reg', 'CD8+ T CD49f+', 'CD8+ T CD57+ CD45RA+', 'CD8+ T CD69+ CD45RO+', 'CD8+ T TIGIT+ CD45RA+', 'CD8+ T CD69+ CD45RA+', 'CD8+ T TIGIT+ CD45RO+', 'gdT TCRVD2+', 'CD4+ T CD314+ CD45RA+', 'CD8+ T naive CD127+ CD26- CD101-', 'gdT CD158b+', 'CD8+ T CD57+ CD45RO+', 'dnT', 'T prog cycling')] <- "T"

meta$broad_cell_type[meta$cell_type %in% c('Naive CD20+ B IGKC+', 'Naive CD20+ B IGKC-', 'B1 B IGKC-', 'B1 B IGKC+', 'Transitional B')] <- "B"

meta$broad_cell_type[meta$cell_type %in% c('NK CD158e1+', 'NK')] <- "NK cells"


meta$broad_cell_type[meta$cell_type %in% c('cDC2', 'pDCs', 'pDC')] <- "DCs"

meta$broad_cell_type[meta$cell_type %in% c('CD14+ Mono', 'CD16+ Mono')] <- "Monocytes"

meta$broad_cell_type[meta$cell_type %in% c('Proerythroblast', 'Erythroblast', 'Normoblast/Reticulocyte')] <- "Erythro"

meta$broad_cell_type[meta$cell_type %in% c('ILC', 'MK/E prog', 'HSC', 'Lymph prog', 'G/M prog')] <- "Progenitors"

unique(meta$cell_type[ is.na(meta$broad_cell_type)])

}

table(meta$broad_cell_type, useNA = "ifany")

DF <- adt_real %>% full_join(adt_predicted_sclinear, by = c("gene", "cell")) %>% full_join(meta, by = c("cell"))

#######
PBMC <- DF
#PBMC <- na.omit(PBMC)

cors <- PBMC %>% group_by(gene) %>% dplyr::summarise(correlation = cor(real, predicted_sclinear))
ggplot(cors, aes(x=reorder(gene, correlation), y= correlation,fill=correlation)) + geom_bar(stat="identity", col="black") + coord_flip() +
    theme_classic2() + scale_fill_gradientn(colours = inferno(11)) + ylab("Pearson\n(Real vs ScLinear)") + xlab("Protein") + theme(legend.position = "none") +
    ggtitle("Neurips CITE-seq\n(n cells)") + theme(plot.title = element_text(hjust = 0.5)) +
    theme( axis.text.y = element_text(size = 8)) + ylim(c(NA,1))


ggsave("./../local/neurips.pearson.pdf", height = 35, width =20, units = "cm", device = "pdf" )



# 
# 
# 
# 
# 
# 
# #Naive CD20+ B IGKC+
# 
# 
# 
# unique(meta$cell_type[ is.na(meta$broad_cell_type)])
# 
# 
# 
# 
# 
# 
# DF <- adt_real %>% full_join(adt_predicted_sclinear, by = c("gene", "cell"))  %>%  full_join(meta, by = c("cell"))
# 
# DF <- DF %>% arrange(gene)
# 
# DF$gene <- factor(DF$gene, levels = unique(DF$gene))
# 
# 
# 
# sobj_test
# 
# 
# eval_res <- evaluate_predictor(pipe, sobj_test@assays$RNA, sobj_test@assays$ADT, normalize_gex = FALSE, normalize_adt = FALSE, slot = "data")
# 
# pbmc10k[["predicted_adt_sclinear"]] <- assay_predicted
# 
# # saveRDS(pbmc10k, "./../local/PBMC10K_predicted.rds")
# # rm(assay_predicted, eval_res,pipe, pbmc10k)
# # gc()

```

```{r}
my_pal <- c("#E7E7E0","#A2A187", "#525240", "#03878F", "#F2B531","#ED5958","#68C6A4", "#113245")
PBMC2 <- filter(PBMC, gene %in% c("CD19","CD3","CD14","CD56"))
ggplot(PBMC2, aes(x=predicted_sclinear, y=real, col=cell_type)) + geom_point(alpha = 0.8, size=0.5) + facet_wrap(~gene, scales = "free") +
  #scale_color_manual(values = my_pal[5:8]) +
  theme_classic2() + theme(legend.title = element_blank()) +
  geom_smooth(method=lm, se=FALSE, col=my_pal[2], alpha = 0.5) + geom_rug() +
  xlab("ScLinear - Predicted") + ylab("Real")


PBMC2 <- filter(PBMC, gene %in% c("CD19","CD3","CD14","CD56"))
ggplot(PBMC2, aes(x=predicted_sclinear, y=real, col=broad_cell_type)) + geom_point(alpha = 0.8, size=0.5) + facet_wrap(~gene, scales = "free") +
  #scale_color_manual(values = my_pal[5:8]) +
  theme_classic2() + theme(legend.title = element_blank()) +
  geom_smooth(method=lm, se=FALSE, col=my_pal[2], alpha = 0.5) + geom_rug() +
  xlab("ScLinear - Predicted") + ylab("Real")



```